### PR TITLE
Update dotenv semver range

### LINKED ISSUE #46: depend to dotenv with ^
There will be a less amount of greenkeeper PRs.

### PR DESCRIPTION
**Pull request by cemremengu**
Closes #46

### CODE REVIEW

**Comment by cemremengu** [comment]
@mcollina I don't have permission for this one

**Comment by mcollina** [comment]
I don't have publish rights either.

@allevo can you add me to https://www.npmjs.com/package/fastify-env owners? So I'll put this in the npm org.

Also, who are `daaaaa` and `jgiola` on npm? They can publish releases to npm but they don't have write access to this repo. I'm fine in them being maintainer, as long as they have write access here as well.

**Comment by allevo** [comment]
They are my colleagues.

I've add you to the `fastify-env` project

**Comment by mcollina** [comment]
Add them to this repo as well ;).

**Pull request merged**
